name: Check PR Release Notes

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]
    branches: [ master ]

jobs:
  check-release-notes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.14'

      - name: Check presence of release notes in PR body
        uses: AbsaOSS/release-notes-presence-check@8e586b26a5e27f899ee8590a5d988fd4780a3dbf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github-repository: ${{ github.repository }}
          pr-number: ${{ github.event.number }}
          title: "## [Rr]elease [Nn]otes"
          skip-labels: 'no RN'
          skip-placeholders: 'TBD'
